export const AUTH = "AUTH";
export const AUTH_REQUEST = "AUTH_REQUEST";
export const LOGOUT = "LOGOUT";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_BY_SEARCH = "GET_CONTACTS_BY_SEARCH";
export const CREATE_CONTACT = "CREATE_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
